
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/template?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0
    database: 0
  thymeleaf:
    cache: false
    prefix : classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: LEGACYHTML5
# 配置日志打印级别
logging:
  level:
    com:
      example:
        template: debug
        mapper: debug
mybatis:
  mapper-locations: classpath:config/mapper/*.xml
  type-aliases-package: com.example.template.common.entity